version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PG_URL=postgres://pokedex_admin:pokedex@db:5432/pokedex
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: poke
      POSTGRES_PASSWORD: pokemon
      POSTGRES_DB: pokepokedex
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: